import { and, desc, eq } from "drizzle-orm";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { academicYears, auditEvents, classes, enrollmentFinancialAccounts, enrollments, financeExchangeRates, financeFeeSchedules, studentPayments, students, users } from "../../drizzle/schema";
import { canTransitionPayment, convertToCdf, displayUsd, nextBalance } from "../financeEngine";
import { getDb } from "../db";
import { assertPermission } from "../permissions";
import { adminProcedure, router } from "../_core/trpc";

async function database() { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "La base de données financière n’est pas disponible." }); return db; }

async function paymentContext(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, paymentId: number) {
  const [payment] = await db.select({ id: studentPayments.id, enrollmentId: studentPayments.enrollmentId, amount: studentPayments.amount, status: studentPayments.status, reference: studentPayments.reference, receiptNumber: studentPayments.receiptNumber, payerName: studentPayments.payerName, sourceCurrency: studentPayments.sourceCurrency, sourceAmount: studentPayments.sourceAmount, exchangeRate: studentPayments.exchangeRateCdfPerUnit, amountBefore: studentPayments.amountBefore, amountAfter: studentPayments.amountAfter, paidAt: studentPayments.paidAt, validatedAt: studentPayments.validatedAt, validatedByUserId: studentPayments.validatedByUserId, academicYearId: enrollments.academicYearId, studentCode: students.studentCode, studentFirstName: students.firstName, studentLastName: students.lastName, className: classes.name, expectedAmount: enrollmentFinancialAccounts.expectedAmount, paidAmount: enrollmentFinancialAccounts.paidAmount }).from(studentPayments).innerJoin(enrollments, eq(studentPayments.enrollmentId, enrollments.id)).innerJoin(students, eq(enrollments.studentId, students.id)).leftJoin(classes, eq(enrollments.classId, classes.id)).innerJoin(enrollmentFinancialAccounts, eq(studentPayments.enrollmentId, enrollmentFinancialAccounts.enrollmentId)).where(eq(studentPayments.id, paymentId)).limit(1);
  if (!payment) throw new TRPCError({ code: "NOT_FOUND", message: "Paiement introuvable." });
  return payment;
}

export const financeRouter = router({
  fees: router({
    list: adminProcedure.input(z.object({ academicYearId: z.number().int().positive() })).query(async ({ ctx, input }) => { await assertPermission(ctx.user.id, "finance", "view"); return (await database()).select().from(financeFeeSchedules).where(eq(financeFeeSchedules.academicYearId, input.academicYearId)); }),
    save: adminProcedure.input(z.object({ academicYearId: z.number().int().positive(), section: z.string().trim().min(2).max(80), expectedAmountCdf: z.number().int().positive(), active: z.boolean().default(true) })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user.id, "finance", "edit"); const db = await database(); await db.insert(financeFeeSchedules).values({ ...input, createdByUserId: ctx.user.id }).onDuplicateKeyUpdate({ set: { expectedAmountCdf: input.expectedAmountCdf, active: input.active } }); await db.insert(auditEvents).values({ actorUserId: ctx.user.id, action: "finance_fee_schedule_saved", module: "finance", resourceType: "academic_year", resourceId: input.academicYearId, afterState: JSON.stringify(input) }); return { ok: true }; }),
  }),
  exchangeRates: router({
    save: adminProcedure.input(z.object({ academicYearId: z.number().int().positive(), cdfPerUnit: z.number().int().positive() })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user.id, "finance", "edit"); const db = await database(); await db.update(financeExchangeRates).set({ active: false }).where(and(eq(financeExchangeRates.academicYearId, input.academicYearId), eq(financeExchangeRates.active, true))); await db.insert(financeExchangeRates).values({ academicYearId: input.academicYearId, cdfPerUnit: input.cdfPerUnit, createdByUserId: ctx.user.id }); await db.insert(auditEvents).values({ actorUserId: ctx.user.id, action: "finance_exchange_rate_saved", module: "finance", resourceType: "academic_year", resourceId: input.academicYearId, afterState: JSON.stringify(input) }); return { ok: true }; }),
  }),
  accounts: router({
    configure: adminProcedure.input(z.object({ enrollmentId: z.number().int().positive(), expectedAmountCdf: z.number().int().positive() })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user.id, "finance", "edit"); const db = await database(); const [account] = await db.select({ paidAmount: enrollmentFinancialAccounts.paidAmount }).from(enrollmentFinancialAccounts).where(eq(enrollmentFinancialAccounts.enrollmentId, input.enrollmentId)).limit(1); if (account && input.expectedAmountCdf < account.paidAmount) throw new TRPCError({ code: "BAD_REQUEST", message: "Le montant prévu ne peut pas être inférieur aux paiements déjà validés." }); await db.insert(enrollmentFinancialAccounts).values({ enrollmentId: input.enrollmentId, expectedAmount: input.expectedAmountCdf, paidAmount: account?.paidAmount ?? 0, currency: "CDF" }).onDuplicateKeyUpdate({ set: { expectedAmount: input.expectedAmountCdf } }); await db.insert(auditEvents).values({ actorUserId: ctx.user.id, action: "finance_account_configured", module: "finance", resourceType: "enrollment", resourceId: input.enrollmentId, afterState: JSON.stringify(input) }); return { ok: true }; }),
  }),
  payments: router({
    create: adminProcedure.input(z.object({ enrollmentId: z.number().int().positive(), reference: z.string().trim().min(3).max(80), payerName: z.string().trim().min(2).max(180), sourceCurrency: z.enum(["CDF", "USD"]), sourceAmount: z.number().int().positive(), paidAt: z.coerce.date().optional() })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user.id, "finance", "create"); const db = await database(); const [enrollment] = await db.select({ academicYearId: enrollments.academicYearId }).from(enrollments).where(eq(enrollments.id, input.enrollmentId)).limit(1); if (!enrollment) throw new TRPCError({ code: "NOT_FOUND", message: "Inscription annuelle introuvable." }); const [rate] = input.sourceCurrency === "USD" ? await db.select({ cdfPerUnit: financeExchangeRates.cdfPerUnit }).from(financeExchangeRates).where(and(eq(financeExchangeRates.academicYearId, enrollment.academicYearId), eq(financeExchangeRates.active, true))).orderBy(desc(financeExchangeRates.id)).limit(1) : []; let conversion; try { conversion = convertToCdf(input.sourceAmount, input.sourceCurrency, rate?.cdfPerUnit); } catch (error) { throw new TRPCError({ code: "BAD_REQUEST", message: (error as Error).message }); } await db.insert(studentPayments).values({ enrollmentId: input.enrollmentId, amount: conversion.amountCdf, currency: "CDF", sourceCurrency: input.sourceCurrency, sourceAmount: input.sourceAmount, exchangeRateCdfPerUnit: conversion.rate, reference: input.reference, payerName: input.payerName, status: "pending", paidAt: input.paidAt ?? new Date(), recordedByUserId: ctx.user.id }); const [payment] = await db.select({ id: studentPayments.id }).from(studentPayments).where(eq(studentPayments.reference, input.reference)).limit(1); if (!payment) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Le paiement n’a pas été enregistré." }); await db.insert(auditEvents).values({ actorUserId: ctx.user.id, action: "finance_payment_created", module: "finance", resourceType: "payment", resourceId: payment.id, afterState: JSON.stringify({ ...input, amountCdf: conversion.amountCdf, rate: conversion.rate }) }); return payment; }),
    validate: adminProcedure.input(z.object({ paymentId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user.id, "finance", "validate"); const db = await database(); const payment = await paymentContext(db, input.paymentId); if (!canTransitionPayment(payment.status as "pending" | "validated" | "rejected" | "cancelled", "validated")) throw new TRPCError({ code: "BAD_REQUEST", message: "Seul un paiement en attente peut être validé." }); let balances; try { balances = nextBalance(payment.expectedAmount, payment.paidAmount, payment.amount); } catch (error) { throw new TRPCError({ code: "BAD_REQUEST", message: (error as Error).message }); } const receiptNumber = `REC-${payment.academicYearId}-${String(payment.id).padStart(8, "0")}`; await db.transaction(async (tx) => { await tx.update(studentPayments).set({ status: "validated", amountBefore: balances.before, amountAfter: balances.after, receiptNumber, validatedByUserId: ctx.user.id, validatedAt: new Date() }).where(eq(studentPayments.id, payment.id)); await tx.update(enrollmentFinancialAccounts).set({ paidAmount: balances.paidAfter }).where(eq(enrollmentFinancialAccounts.enrollmentId, payment.enrollmentId)); }); await db.insert(auditEvents).values({ actorUserId: ctx.user.id, action: "finance_payment_validated", module: "finance", resourceType: "payment", resourceId: payment.id, afterState: JSON.stringify({ receiptNumber, ...balances }) }); return { receiptNumber, ...balances }; }),
    reject: adminProcedure.input(z.object({ paymentId: z.number().int().positive(), reason: z.string().trim().min(3).max(1000) })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user.id, "finance", "validate"); const db = await database(); const payment = await paymentContext(db, input.paymentId); if (!canTransitionPayment(payment.status as "pending" | "validated" | "rejected" | "cancelled", "rejected")) throw new TRPCError({ code: "BAD_REQUEST", message: "Seul un paiement en attente peut être rejeté." }); await db.update(studentPayments).set({ status: "rejected", statusReason: input.reason, rejectedAt: new Date() }).where(eq(studentPayments.id, payment.id)); await db.insert(auditEvents).values({ actorUserId: ctx.user.id, action: "finance_payment_rejected", module: "finance", resourceType: "payment", resourceId: payment.id, reason: input.reason }); return { ok: true }; }),
    cancel: adminProcedure.input(z.object({ paymentId: z.number().int().positive(), reason: z.string().trim().min(3).max(1000) })).mutation(async ({ ctx, input }) => { await assertPermission(ctx.user.id, "finance", "cancel"); const db = await database(); const payment = await paymentContext(db, input.paymentId); if (!canTransitionPayment(payment.status as "pending" | "validated" | "rejected" | "cancelled", "cancelled")) throw new TRPCError({ code: "BAD_REQUEST", message: "Seul un paiement en attente ou validé peut être annulé." }); if (payment.status === "validated" && payment.paidAmount < payment.amount) throw new TRPCError({ code: "BAD_REQUEST", message: "Le solde comptable ne permet pas cette annulation." }); await db.transaction(async (tx) => { await tx.update(studentPayments).set({ status: "cancelled", statusReason: input.reason, cancelledAt: new Date() }).where(eq(studentPayments.id, payment.id)); if (payment.status === "validated") await tx.update(enrollmentFinancialAccounts).set({ paidAmount: payment.paidAmount - payment.amount }).where(eq(enrollmentFinancialAccounts.enrollmentId, payment.enrollmentId)); }); await db.insert(auditEvents).values({ actorUserId: ctx.user.id, action: "finance_payment_cancelled", module: "finance", resourceType: "payment", resourceId: payment.id, reason: input.reason }); return { ok: true }; }),
    receipt: adminProcedure.input(z.object({ paymentId: z.number().int().positive() })).query(async ({ ctx, input }) => { await assertPermission(ctx.user.id, "finance", "print"); const db = await database(); const payment = await paymentContext(db, input.paymentId); if (payment.status !== "validated" || !payment.receiptNumber) throw new TRPCError({ code: "BAD_REQUEST", message: "Un reçu officiel exige un paiement validé." }); const [validator] = payment.validatedByUserId ? await db.select({ name: users.name }).from(users).where(eq(users.id, payment.validatedByUserId)).limit(1) : []; await db.insert(auditEvents).values({ actorUserId: ctx.user.id, action: "finance_receipt_printed", module: "finance", resourceType: "payment", resourceId: payment.id }); return { ...payment, validatorName: validator?.name ?? null, amountUsd: displayUsd(payment.amount, payment.exchangeRate ?? null) }; }),
    export: adminProcedure.input(z.object({ academicYearId: z.number().int().positive() })).query(async ({ ctx, input }) => { await assertPermission(ctx.user.id, "finance", "export"); const db = await database(); const rows = await db.select({ id: studentPayments.id, reference: studentPayments.reference, receiptNumber: studentPayments.receiptNumber, amountCdf: studentPayments.amount, sourceCurrency: studentPayments.sourceCurrency, sourceAmount: studentPayments.sourceAmount, exchangeRate: studentPayments.exchangeRateCdfPerUnit, status: studentPayments.status, studentCode: students.studentCode, studentFirstName: students.firstName, studentLastName: students.lastName, className: classes.name }).from(studentPayments).innerJoin(enrollments, eq(studentPayments.enrollmentId, enrollments.id)).innerJoin(students, eq(enrollments.studentId, students.id)).leftJoin(classes, eq(enrollments.classId, classes.id)).where(eq(enrollments.academicYearId, input.academicYearId)); await db.insert(auditEvents).values({ actorUserId: ctx.user.id, action: "finance_payments_exported", module: "finance", resourceType: "academic_year", resourceId: input.academicYearId, afterState: JSON.stringify({ count: rows.length }) }); return rows.map((row) => ({ ...row, amountUsd: displayUsd(row.amountCdf, row.exchangeRate ?? null) })); }),
  }),
});
