import { BarChart3, CheckCircle2, CircleDollarSign, ClipboardCheck, FileWarning, GraduationCap, Loader2, RefreshCw, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const formatCurrency = (value: number) => `${new Intl.NumberFormat("fr-FR").format(value)} CDF`;

export function AnnualControlCenter({ onNavigate }: { onNavigate: (label: string) => void }) {
  const years = trpc.school.years.list.useQuery();
  const [yearId, setYearId] = useState<string>("");
  useEffect(() => { if (!yearId && years.data?.[0]) setYearId(String(years.data[0].id)); }, [yearId, years.data]);
  const summary = trpc.annualControl.summary.useQuery({ academicYearId: Number(yearId) }, { enabled: Boolean(yearId) });
  const data = summary.data;
  const openWorkflow = (label: string) => onNavigate(label);
  if (years.isLoading || summary.isLoading) return <section className="module-shell annual-control"><div className="annual-loading"><Loader2 className="animate-spin" size={22} /><span>Consolidation du contrôle annuel…</span></div></section>;
  if (summary.error) return <section className="module-shell annual-control"><div className="annual-empty"><FileWarning size={27} /><h1>Contrôle annuel indisponible</h1><p>{summary.error.message}</p><Button variant="outline" onClick={() => summary.refetch()}><RefreshCw size={15} /> Réessayer</Button></div></section>;
  if (!data) return <section className="module-shell annual-control"><div className="annual-empty"><GraduationCap size={27} /><h1>Aucune année disponible</h1><p>Créez ou sélectionnez une année scolaire pour consolider ses indicateurs.</p></div></section>;
  const gradeTotal = data.grades.draft + data.grades.submitted + data.grades.validated;
  const reportTotal = data.reports.draft + data.reports.submitted + data.reports.validated;
  const decisionTotal = data.decisions.draft + data.decisions.proposed + data.decisions.validated;
  return <section className="module-shell annual-control">
    <header className="module-shell-heading"><div><p className="eyebrow">Pilotage institutionnel</p><h1>Contrôle annuel</h1><p>Consolidation des registres pédagogiques, financiers et de délibération. Les décisions restent séparées des notes.</p></div><ShieldCheck size={28} /></header>
    <div className="annual-toolbar"><div><span>Année analysée</span><Select value={yearId} onValueChange={setYearId}><SelectTrigger><SelectValue placeholder="Sélectionner une année" /></SelectTrigger><SelectContent>{years.data?.map((year) => <SelectItem value={String(year.id)} key={year.id}>{year.label}</SelectItem>)}</SelectContent></Select></div><Button variant="outline" onClick={() => summary.refetch()}><RefreshCw size={15} /> Actualiser</Button></div>
    <div className="annual-status-line"><span className={`annual-year-status ${data.year.status}`}>{data.year.status === "active" ? "Année active" : data.year.status}</span><span>{data.enrollmentCount} inscription{data.enrollmentCount > 1 ? "s" : ""} active{data.enrollmentCount > 1 ? "s" : ""}</span><span>Période : {new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(new Date(data.year.startsAt))} — {new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(new Date(data.year.endsAt))}</span></div>
    <div className="annual-metric-grid"><article><span className="annual-metric-icon"><BarChart3 size={19} /></span><p>Notes à valider</p><strong>{data.grades.submitted}</strong><small>{data.grades.draft} brouillon{data.grades.draft > 1 ? "s" : ""} · {data.grades.validated} validée{data.grades.validated > 1 ? "s" : ""}</small><button onClick={() => openWorkflow("Notes")}>Ouvrir les notes</button></article><article><span className="annual-metric-icon gold"><ClipboardCheck size={19} /></span><p>Rapports à traiter</p><strong>{data.reports.submitted}</strong><small>{data.reports.draft} brouillon{data.reports.draft > 1 ? "s" : ""} · {data.reports.validated} validé{data.reports.validated > 1 ? "s" : ""}</small><button onClick={() => openWorkflow("Rapports")}>Ouvrir les rapports</button></article><article><span className="annual-metric-icon green"><CircleDollarSign size={19} /></span><p>Encaissement</p><strong>{data.finance.collectionRate.toLocaleString("fr-FR")} %</strong><small>{formatCurrency(data.finance.paidAmount)} sur {formatCurrency(data.finance.expectedAmount)}</small><button onClick={() => openWorkflow("Paiements")}>Voir les paiements</button></article><article><span className="annual-metric-icon red"><CheckCircle2 size={19} /></span><p>Décisions à valider</p><strong>{data.decisions.proposed}</strong><small>{data.decisions.validated} validée{data.decisions.validated > 1 ? "s" : ""} · {data.decisions.draft} brouillon{data.decisions.draft > 1 ? "s" : ""}</small><button onClick={() => openWorkflow("Examens")}>Ouvrir la délibération</button></article></div>
    <div className="annual-register-grid"><article className="annual-register"><div className="annual-section-heading"><div><p className="eyebrow">Registre pédagogique</p><h2>État des saisies</h2></div><span>{gradeTotal} enregistrement{gradeTotal > 1 ? "s" : ""}</span></div><StatusRow label="Brouillons de notes" value={data.grades.draft} total={gradeTotal} tone="neutral" /><StatusRow label="Notes soumises" value={data.grades.submitted} total={gradeTotal} tone="warning" /><StatusRow label="Notes validées" value={data.grades.validated} total={gradeTotal} tone="success" /><div className="annual-divider" /><StatusRow label="Rapports brouillons" value={data.reports.draft} total={reportTotal} tone="neutral" /><StatusRow label="Rapports soumis" value={data.reports.submitted} total={reportTotal} tone="warning" /><StatusRow label="Rapports validés" value={data.reports.validated} total={reportTotal} tone="success" /></article><article className="annual-register annual-decision-register"><div className="annual-section-heading"><div><p className="eyebrow">Cycle annuel</p><h2>Deuxième session et délibération</h2></div><span>{decisionTotal} décision{decisionTotal > 1 ? "s" : ""}</span></div>{data.secondSession ? <div className="annual-session-card"><strong>Deuxième session · {data.secondSession.status}</strong><p>Seuil d’éligibilité : {data.secondSession.thresholdPercent} %.</p><dl><div><dt>Inscriptions</dt><dd>{data.secondSession.registrationDeadline ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(new Date(data.secondSession.registrationDeadline)) : "Non définies"}</dd></div><div><dt>Épreuves</dt><dd>{data.secondSession.examStartsAt ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(new Date(data.secondSession.examStartsAt)) : "Non définies"}</dd></div></dl></div> : <div className="annual-session-card is-empty"><strong>Aucune deuxième session configurée</strong><p>La configuration annuelle peut être créée depuis le cycle des examens.</p></div>}<StatusRow label="Décisions brouillons" value={data.decisions.draft} total={decisionTotal} tone="neutral" /><StatusRow label="Décisions proposées" value={data.decisions.proposed} total={decisionTotal} tone="warning" /><StatusRow label="Décisions validées" value={data.decisions.validated} total={decisionTotal} tone="success" /><div className="annual-alert"><FileWarning size={18} /><p>{data.decisions.proposed ? `${data.decisions.proposed} décision${data.decisions.proposed > 1 ? "s" : ""} attendent encore une validation formelle.` : "Aucune décision proposée en attente de validation."}</p></div></article></div>
  </section>;
}

function StatusRow({ label, value, total, tone }: { label: string; value: number; total: number; tone: "neutral" | "warning" | "success" }) { const percentage = total ? Math.round((value / total) * 100) : 0; return <div className="annual-status-row"><div><span className={`annual-dot ${tone}`} /><strong>{label}</strong></div><b>{value}</b><div className="annual-progress"><i className={tone} style={{ width: `${percentage}%` }} /></div><small>{percentage} %</small></div>; }
