/**
 * Direction visuelle : « Registre diocésain contemporain » — un poste de travail de classe
 * qui relie les opérations quotidiennes aux indicateurs annuels de 7e A.
 */
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowLeft, BookOpenCheck, CalendarDays, CheckCircle2, ChevronRight, ClipboardCheck, FileText, GraduationCap, Plus, Search, UsersRound, UserPlus } from "lucide-react";
import { useState } from "react";

type ClassTab = "students" | "courses" | "teachers" | "attendance" | "results" | "reports";
const tabs: { id: ClassTab; label: string }[] = [{ id: "students", label: "Élèves" }, { id: "courses", label: "Cours" }, { id: "teachers", label: "Enseignants" }, { id: "attendance", label: "Présences" }, { id: "results", label: "Résultats" }, { id: "reports", label: "Rapports" }];
const roster = [{ initials: "JK", name: "Jean Kabila", code: "STU-000145", sex: "M", status: "Actif", average: "15,7 / 20", rank: "6e", balance: "185 000 CDF" }, { initials: "SM", name: "Sarah Mbayo", code: "STU-000146", sex: "F", status: "Actif", average: "16,4 / 20", rank: "3e", balance: "À jour" }, { initials: "GM", name: "Grâce Mulumba", code: "STU-000147", sex: "F", status: "Actif", average: "14,8 / 20", rank: "11e", balance: "40 000 CDF" }, { initials: "DK", name: "David Kanku", code: "STU-000152", sex: "M", status: "Actif", average: "13,5 / 20", rank: "18e", balance: "À jour" }, { initials: "BN", name: "Bénédicte Nsimba", code: "STU-000149", sex: "F", status: "En attente", average: "—", rank: "—", balance: "À jour" }];
const courses = [{ course: "Mathématiques", teacher: "M. Patrick Kabila", period: "10 points", exam: "20 points", semester: "40 points", status: "Configuré" }, { course: "Français", teacher: "Mme Marie Nsimba", period: "10 points", exam: "20 points", semester: "40 points", status: "Configuré" }, { course: "Anglais", teacher: "M. Jean Kabasele", period: "10 points", exam: "20 points", semester: "40 points", status: "Configuré" }, { course: "Histoire", teacher: "Mme Nicole Bemba", period: "5 points", exam: "10 points", semester: "20 points", status: "Configuré" }];
const teachers = [{ name: "M. Patrick Kabila", course: "Mathématiques", coverage: "P1 · P2 · Examen", notes: "À jour" }, { name: "Mme Marie Nsimba", course: "Français", coverage: "P1 · P2 · Examen", notes: "À jour" }, { name: "M. Jean Kabasele", course: "Anglais", coverage: "P1 · P2 · Examen", notes: "À compléter" }, { name: "Mme Nicole Bemba", course: "Histoire", coverage: "P1 · P2 · Examen", notes: "À jour" }];
const resultData = [{ name: "Math.", average: 15.8 }, { name: "Français", average: 14.6 }, { name: "Anglais", average: 13.9 }, { name: "Histoire", average: 15.1 }, { name: "Sciences", average: 14.3 }];

export function ClassWorkspace({ onBack, onToast, onNavigate }: { onBack: () => void; onToast: (title: string, description: string) => void; onNavigate: (label: string) => void }) {
  const [activeTab, setActiveTab] = useState<ClassTab>(() => new URLSearchParams(window.location.search).get("onglet-classe") === "cours" ? "courses" : "students");
  const [search, setSearch] = useState("");
  const filteredRoster = roster.filter((student) => !search || `${student.name} ${student.code}`.toLowerCase().includes(search.toLowerCase()));
  const overview = <div className="class-workspace-overview"><div className="class-metric-strip"><div><span>34</span><small>élèves inscrits</small></div><div><span>12</span><small>cours configurés</small></div><div><span>8</span><small>enseignants affectés</small></div><div><span>96,2 %</span><small>présence actuelle</small></div><div><span>14,7 / 20</span><small>moyenne de classe</small></div></div></div>;
  const students = <section className="workspace-section"><div className="workspace-table-toolbar"><div><p className="eyebrow">Élèves · 7e A</p><h2>Registre des inscriptions</h2></div><div className="workspace-search"><Search size={15} /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher un élève" /></div></div><div className="workspace-table-wrap"><table className="workspace-table"><thead><tr><th><Checkbox aria-label="Sélectionner les élèves" /></th><th>Photo</th><th>Matricule</th><th>Nom complet</th><th>Sexe</th><th>Statut</th><th>Moyenne</th><th>Rang</th><th>Solde</th></tr></thead><tbody>{filteredRoster.map((student) => <tr key={student.code}><td><Checkbox aria-label={`Sélectionner ${student.name}`} /></td><td><span className={`student-photo student-photo-${student.sex.toLowerCase()}`}>{student.initials}</span></td><td><strong className="student-code">{student.code}</strong></td><td><strong>{student.name}</strong></td><td>{student.sex}</td><td><Badge className={`status-badge ${student.status === "Actif" ? "success" : "warning"}`}>{student.status}</Badge></td><td><strong>{student.average}</strong></td><td>{student.rank}</td><td><strong className={student.balance === "À jour" ? "balance" : "balance balance-high"}>{student.balance}</strong></td></tr>)}</tbody></table></div></section>;
  const coursesTab = <section className="workspace-section"><div className="workspace-table-toolbar"><div><p className="eyebrow">Configuration annuelle</p><h2>Cours enseignés en 7e A</h2></div><Button variant="outline" className="secondary-action" onClick={() => onNavigate("Cours et pondérations")}><BookOpenCheck size={15} /> Gérer les pondérations</Button></div><div className="workspace-table-wrap"><table className="workspace-table"><thead><tr><th>Cours</th><th>Enseignant(s)</th><th>Pondération / période</th><th>Examen</th><th>Total semestre</th><th>Statut</th></tr></thead><tbody>{courses.map((course) => <tr key={course.course}><td><strong>{course.course}</strong></td><td>{course.teacher}</td><td>{course.period}</td><td>{course.exam}</td><td>{course.semester}</td><td><Badge className="status-badge success">{course.status}</Badge></td></tr>)}</tbody></table></div></section>;
  const teachersTab = <section className="workspace-section"><div className="workspace-table-toolbar"><div><p className="eyebrow">Affectations actives</p><h2>Enseignants de 7e A</h2></div><Button variant="outline" className="secondary-action" onClick={() => onNavigate("Affectations")}><UserPlus size={15} /> Gérer les affectations</Button></div><div className="teacher-assignment-list">{teachers.map((teacher) => <article key={teacher.name}><span className="teacher-avatar">{teacher.name.split(" ").slice(-1)[0].slice(0, 2).toUpperCase()}</span><div><strong>{teacher.name}</strong><small>{teacher.course} · {teacher.coverage}</small></div><Badge className={`status-badge ${teacher.notes === "À jour" ? "success" : "warning"}`}>Notes : {teacher.notes}</Badge></article>)}</div></section>;
  const attendance = <section className="workspace-section"><div className="workspace-table-toolbar"><div><p className="eyebrow">Présences</p><h2>Assiduité de la classe</h2></div><Badge className="status-badge success">96,2 % aujourd’hui</Badge></div><div className="attendance-class-grid"><div><span>34</span><small>présents</small></div><div><span>0</span><small>absent non justifié</small></div><div><span>1</span><small>retard signalé</small></div><div><span>96,2 %</span><small>taux cumulé</small></div></div><div className="attendance-class-log"><div><strong>27 août 2026</strong><span>34 présents · 0 absent · 1 retard</span><Badge className="status-badge success">Validé</Badge></div><div><strong>26 août 2026</strong><span>33 présents · 1 absence justifiée</span><Badge className="status-badge info">Validé</Badge></div><div><strong>25 août 2026</strong><span>34 présents · 0 absence</span><Badge className="status-badge success">Validé</Badge></div></div></section>;
  const results = <section className="workspace-section"><div className="workspace-table-toolbar"><div><p className="eyebrow">Résultats</p><h2>Performance par cours</h2></div><div className="class-result-value"><strong>14,7 / 20</strong><span>moyenne générale</span></div></div><div className="class-result-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={resultData} margin={{ top: 15, right: 10, left: -20, bottom: 0 }} barCategoryGap="35%"><CartesianGrid vertical={false} stroke="#e7edf3" strokeDasharray="3 3" /><XAxis dataKey="name" tick={{ fill: "#7d8b9d", fontSize: 10, fontWeight: 700 }} tickLine={false} axisLine={false} /><YAxis domain={[0, 20]} ticks={[0, 5, 10, 15, 20]} tick={{ fill: "#8b97a6", fontSize: 9 }} tickLine={false} axisLine={false} /><Tooltip formatter={(value: number) => [`${String(value).replace(".", ",")} / 20`, "Moyenne"]} contentStyle={{ border: "1px solid #dbe4ef", borderRadius: "5px", boxShadow: "0 8px 18px rgba(34,52,77,.10)", fontSize: 11 }} /><Bar dataKey="average" fill="#1f4a8a" radius={[2, 2, 0, 0]} maxBarSize={35} /></BarChart></ResponsiveContainer></div></section>;
  const reports = <section className="workspace-section"><div className="workspace-table-toolbar"><div><p className="eyebrow">Rapports enseignants</p><h2>État de soumission</h2></div><Badge className="status-badge warning">1 à relancer</Badge></div><div className="reports-list"><div><span className="report-status ready"><CheckCircle2 size={15} /></span><div><strong>Rapport Mathématiques</strong><small>M. Patrick Kabila · Soumis le 26 août 2026</small></div><Badge className="status-badge success">Validé</Badge></div><div><span className="report-status ready"><CheckCircle2 size={15} /></span><div><strong>Rapport Français</strong><small>Mme Marie Nsimba · Soumis le 25 août 2026</small></div><Badge className="status-badge success">Validé</Badge></div><div><span className="report-status pending"><FileText size={15} /></span><div><strong>Rapport Anglais</strong><small>M. Jean Kabasele · Échéance : 28 août 2026</small></div><Badge className="status-badge warning">À compléter</Badge></div></div></section>;
  const currentContent = activeTab === "students" ? students : activeTab === "courses" ? coursesTab : activeTab === "teachers" ? teachersTab : activeTab === "attendance" ? attendance : activeTab === "results" ? results : reports;
  return <section className="class-workspace-page" aria-label="Espace de travail de la classe 7e A"><button className="profile-back" onClick={onBack}><ArrowLeft size={16} /> Retour aux classes</button><header className="class-workspace-header"><div><p className="eyebrow">Espace de classe · année scolaire 2026-2027</p><h1>7e A</h1><p>Section : Secondaire · Effectif : 34 élèves</p></div><div className="class-workspace-actions"><Button className="primary-action" onClick={() => onToast("Ajout d’élève", "Le formulaire d’inscription pour 7e A est prêt à être ouvert.")}><Plus size={15} /> Ajouter un élève</Button><Button variant="outline" className="secondary-action" onClick={() => setActiveTab("courses")}><BookOpenCheck size={15} /> Configurer les cours</Button><Button variant="outline" className="secondary-action" onClick={() => setActiveTab("teachers")}><UsersRound size={15} /> Gérer les affectations</Button></div></header>{overview}<nav className="class-workspace-tabs">{tabs.map((tab) => <button key={tab.id} className={activeTab === tab.id ? "is-active" : ""} onClick={() => setActiveTab(tab.id)}>{tab.label}</button>)}</nav><div className="class-workspace-content">{currentContent}</div></section>;
}
