import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { AlertCircle, ArrowLeft, BarChart3, BookOpenCheck, CalendarDays, CheckCircle2, ChevronRight, ClipboardCheck, FileText, History, PenLine, Search, Send, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";

type TeacherView = "dashboard" | "teachings" | "students" | "attendance" | "history" | "evaluations" | "grades" | "exam" | "report" | "monitoring" | "validation" | "reportcard" | "results" | "studentresults";
const assignments = [{ id: "7a-math", course: "Mathématiques", className: "7e A", students: 34, notes: "32/34", attendance: "À jour", evaluation: "30/34", report: "À soumettre" }, { id: "8a-math", course: "Mathématiques", className: "8e A", students: 31, notes: "28/31", attendance: "À jour", evaluation: "31/31", report: "À soumettre" }, { id: "9b-phys", course: "Physique", className: "9e B", students: 29, notes: "29/29", attendance: "À jour", evaluation: "29/29", report: "Soumis" }];
const learners = [{ id: 1, name: "Jean Kabila", sex: "M", p1: "8", status: "Présent" }, { id: 2, name: "Sarah Mbayo", sex: "F", p1: "7", status: "Présente" }, { id: 3, name: "Grâce Mulumba", sex: "F", p1: "", status: "Absente" }, { id: 4, name: "David Kanku", sex: "M", p1: "9", status: "Retard" }];
const criteria = ["Discipline", "Participation", "Assiduité", "Travail personnel", "Comportement", "Respect des consignes"];

function Header({ title, detail, onBack }: { title: string; detail: string; onBack?: () => void }) { return <header className="teacher-header">{onBack && <button className="profile-back" onClick={onBack}><ArrowLeft size={16} /> Retour</button>}<p className="eyebrow">Enseignant · 2026-2027 · P1</p><h1>{title}</h1><p>{detail}</p></header>; }
function Chip({ children, tone = "success" }: { children: React.ReactNode; tone?: "success" | "warning" | "info" | "error" }) { return <Badge className={`status-badge ${tone}`}>{children}</Badge>; }

export function TeacherSuite({ view, onNavigate, onToast }: { view: TeacherView; onNavigate: (view: TeacherView) => void; onToast: (title: string, detail: string) => void }) {
  const [display, setDisplay] = useState<"cards" | "list">("cards"); const [attendance, setAttendance] = useState<Record<number, string>>({ 1: "Présent", 2: "Présent", 3: "Absent", 4: "Retard" }); const [notes, setNotes] = useState<Record<number, string>>({ 1: "8", 2: "7", 3: "", 4: "9" }); const [gradeErrors, setGradeErrors] = useState<Record<number, string>>({}); const [submitOpen, setSubmitOpen] = useState(false); const [search, setSearch] = useState("");
  const present = Object.values(attendance).filter((v) => v === "Présent").length; const absent = Object.values(attendance).filter((v) => v === "Absent").length; const late = Object.values(attendance).filter((v) => v === "Retard").length;
  const filtered = learners.filter((s) => s.name.toLowerCase().includes(search.toLowerCase()));
  const updateNote = (studentId: number, raw: string, maximum: number) => { const value = Number(raw); setNotes({ ...notes, [studentId]: raw }); setGradeErrors((current) => ({ ...current, [studentId]: raw === "" ? "La note est requise." : !Number.isFinite(value) || value < 0 ? "La note ne peut pas être négative." : value > maximum ? `La note ne peut pas dépasser ${maximum}.` : "" })); };
  const TeachingCard = ({ item }: { item: typeof assignments[number] }) => <article className="teaching-card"><div><p className="eyebrow">{item.className} · Période actuelle : P1</p><h2>{item.course}</h2><span>{item.students} élèves</span></div><div className="teaching-progress"><span>Notes : <strong>{item.notes} saisies</strong></span><span>Présences : <strong>{item.attendance}</strong></span><span>Évaluations : <strong>{item.evaluation}</strong></span><Chip tone={item.report === "Soumis" ? "success" : "warning"}>Rapport : {item.report}</Chip></div><footer><button onClick={() => onNavigate("grades")}>Saisir les notes</button><button onClick={() => onNavigate("attendance")}>Faire l’appel</button><button onClick={() => onNavigate("evaluations")}>Évaluer les élèves</button><button onClick={() => onNavigate("students")}>Voir les élèves</button><button onClick={() => onNavigate("report")}>Rapport</button></footer></article>;
  if (view === "dashboard") return <section className="teacher-suite"><Header title="Bonjour, M. Kabila" detail="Voici votre activité pédagogique." /><div className="teacher-kpis"><div><span>Mes classes</span><strong>3</strong></div><div><span>Mes cours</span><strong>2</strong></div><div><span>Notes à compléter</span><strong>18</strong></div><div><span>Rapports à soumettre</span><strong>2</strong></div></div><section className="teacher-section"><header><div><p className="eyebrow">Mes enseignements</p><h2>Accès rapide</h2></div><button onClick={() => onNavigate("teachings")}>Voir tous <ArrowLeft size={14} /></button></header><div className="teacher-card-grid">{assignments.map((item) => <TeachingCard key={item.id} item={item} />)}</div></section><section className="teacher-lower"><article><p className="eyebrow">À faire</p><h2>Actions requises</h2><button onClick={() => onNavigate("grades")}>2 notes restent à saisir pour la 7e A.</button><button onClick={() => onNavigate("report")}>Votre rapport P1 pour la 8e A n’est pas encore soumis.</button><button onClick={() => onNavigate("attendance")}>L’appel du jour n’a pas encore été effectué.</button></article><article><p className="eyebrow">Activité récente</p><h2>Mon journal pédagogique</h2><div className="teacher-activity"><span>Notes enregistrées · Mathématiques 8e A</span><span>Appel validé · Physique 9e B</span><span>Évaluation mise à jour · 7e A</span></div></article></section></section>;
  if (view === "teachings") return <section className="teacher-suite"><Header title="Mes enseignements" detail="Seules les classes et les cours qui vous sont affectés sont affichés." onBack={() => onNavigate("dashboard")} /><div className="teacher-filter"><Select defaultValue="Toutes"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Toutes">Classe : Toutes</SelectItem><SelectItem value="7e A">7e A</SelectItem></SelectContent></Select><Select defaultValue="P1"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="P1">Période : P1</SelectItem></SelectContent></Select><button onClick={() => setDisplay(display === "cards" ? "list" : "cards")}>{display === "cards" ? "Vue liste" : "Vue cartes"}</button></div><div className={display === "cards" ? "teacher-card-grid" : "teacher-list"}>{assignments.map((item) => <TeachingCard key={item.id} item={item} />)}</div></section>;
  if (view === "students") return <section className="teacher-suite"><Header title="Élèves — 7e A" detail="Mathématiques · P1 · 34 élèves" onBack={() => onNavigate("teachings")} /><div className="teacher-search"><Search size={16} /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Rechercher un élève…" /></div><div className="teacher-student-list">{filtered.map((student, index) => <article key={student.id}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{student.name}</strong><small>{student.sex} · Mathématiques</small></div><Chip>{student.status}</Chip><strong>Note P1 : {student.p1 || "—"}/10</strong><button onClick={() => onNavigate("grades")}>Saisir</button><button onClick={() => onNavigate("evaluations")}>Évaluer</button></article>)}</div></section>;
  if (view === "attendance") return <section className="teacher-suite teacher-mobile"><Header title="Faire l’appel" detail="23 août 2026 · 7e A · Mathématiques · 34 élèves" onBack={() => onNavigate("teachings")} /><div className="attendance-actions"><Button className="primary-action" onClick={() => setAttendance(Object.fromEntries(learners.map((s) => [s.id, "Présent"])))}>Tout présent</Button><Chip tone="info"><History size={13} /> Modifié il y a 2 min</Chip></div><div className="attendance-fast-list">{learners.map((student) => <article key={student.id}><div><strong>{student.name}</strong><small>N° {String(student.id).padStart(2, "0")}</small></div><div>{["Présent", "Absent", "Retard", "Excusé"].map((status) => <button key={status} className={attendance[student.id] === status ? "is-active" : ""} onClick={() => setAttendance({ ...attendance, [student.id]: status })}>{status}</button>)}</div></article>)}</div><footer className="attendance-save"><span>Présents : <strong>{present}</strong> · Absents : <strong>{absent}</strong> · Retards : <strong>{late}</strong></span><Button className="primary-action" onClick={() => onToast("Appel enregistré", "Les présences de 7e A ont été enregistrées et restent modifiables avec historique.")}>Enregistrer l’appel</Button></footer></section>;
  if (view === "history") return <section className="teacher-suite"><Header title="Historique des présences" detail="7e A · Mathématiques · 2026-2027" onBack={() => onNavigate("attendance")} /><div className="attendance-summary"><div><strong>94,2 %</strong><span>Taux de présence</span></div><div><strong>180</strong><span>Présents</span></div><div><strong>8</strong><span>Absents</span></div><div><strong>4</strong><span>Retards</span></div></div><div className="attendance-history"><button>23 août <span>30 présents · 2 absents · 2 retards</span><ChevronRight /></button><button>22 août <span>32 présents · 1 absent · 1 retard</span><ChevronRight /></button></div></section>;
  if (view === "evaluations") return <section className="teacher-suite"><Header title="Évaluations" detail="7e A · Mathématiques · P1 · Critères définis par l’établissement" onBack={() => onNavigate("teachings")} /><div className="evaluation-grid"><table><thead><tr><th>Élève</th>{criteria.slice(0,4).map((c) => <th key={c}>{c}</th>)}<th>Observation</th></tr></thead><tbody>{learners.map((student) => <tr key={student.id}><td><strong>{student.name}</strong></td>{criteria.slice(0,4).map((c) => <td key={c}><Select defaultValue={student.id === 1 ? "TB" : "B"}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="TB">TB</SelectItem><SelectItem value="B">B</SelectItem><SelectItem value="M">M</SelectItem><SelectItem value="INSUFFICIENT">Insuffisant</SelectItem></SelectContent></Select></td>)}<td><Input placeholder="Observation" /></td></tr>)}</tbody></table></div><div className="teacher-submit"><Button variant="outline" className="secondary-action" onClick={() => onToast("Évaluations enregistrées", "Le brouillon de la classe a été sauvegardé.")}>Enregistrer</Button><Button className="primary-action" onClick={() => onNavigate("students")}>Enregistrer et passer à l’élève suivant</Button></div></section>;
  if (view === "grades" || view === "exam") { const maximum = view === "exam" ? 20 : 10; const label = view === "exam" ? "Saisie de l’examen" : "Saisie des notes"; const entered = Object.values(notes).filter(Boolean).length; const missing = learners.filter((student) => !notes[student.id]); const invalid = Object.values(gradeErrors).some(Boolean); const requestSubmission = () => { const required = Object.fromEntries(learners.filter((student) => !notes[student.id]).map((student) => [student.id, "La note est requise."])); setGradeErrors({ ...gradeErrors, ...required }); if (missing.length || invalid) return; setSubmitOpen(true); }; return <section className="teacher-suite"><Header title={label} detail={`7e A · Mathématiques · ${view === "exam" ? "Examen 1" : "P1"} · Note maximale : ${maximum} points`} onBack={() => onNavigate("teachings")} /><div className="grade-summary"><span>34 élèves</span><span>{entered} notes saisies</span><span>{34-entered} notes restantes</span><span>Enregistré il y a moins d’une minute</span></div><div className="grade-entry-list">{learners.map((student, index) => <article key={student.id}><span>{String(index + 1).padStart(2,"0")}</span><strong>{student.name}</strong><div><Input aria-invalid={Boolean(gradeErrors[student.id])} type="number" min="0" max={maximum} value={notes[student.id]} onChange={(e) => updateNote(student.id, e.target.value, maximum)} placeholder={`/${maximum}`} />{gradeErrors[student.id] && <small className="grade-field-error">{gradeErrors[student.id]}</small>}</div><Chip tone={notes[student.id] && !gradeErrors[student.id] ? "success" : "warning"}>{notes[student.id] && !gradeErrors[student.id] ? "Saisie" : "À compléter"}</Chip></article>)}</div><div className="teacher-submit"><Button variant="outline" className="secondary-action" onClick={() => onToast("Brouillon enregistré", "Les notes saisies sont conservées en brouillon.")}>Enregistrer le brouillon</Button><Button className="primary-action" onClick={requestSubmission}>Soumettre les notes</Button></div><Dialog open={submitOpen} onOpenChange={setSubmitOpen}><DialogContent><DialogHeader><DialogTitle>Confirmer la soumission</DialogTitle></DialogHeader><p>Vous êtes sur le point de soumettre les notes de {view === "exam" ? "l’examen 1" : "P1"} pour Mathématiques — 7e A. Après soumission, toute modification nécessitera une autorisation.</p><DialogFooter><Button variant="outline" onClick={() => setSubmitOpen(false)}>Annuler</Button><Button className="primary-action" onClick={() => { setSubmitOpen(false); onToast("Notes soumises", "La soumission a été transmise à l’administration pour validation."); }}>Confirmer la soumission</Button></DialogFooter></DialogContent></Dialog></section>; }
  if (view === "report") return <section className="teacher-suite"><Header title="Rapport de période" detail="M. Patrick Kabila · 7e A · Mathématiques · P1" onBack={() => onNavigate("teachings")} /><div className="teacher-report-form"><label>Déroulement du cours<Textarea placeholder="Décrivez le déroulement du cours…" /></label><div><label>Programme prévu<Textarea /></label><label>Programme réalisé<Textarea /></label><label>Pourcentage approximatif<Input type="number" placeholder="0 à 100" /></label></div><label>Difficultés rencontrées<Textarea /></label><label>Participation générale<Select defaultValue="B"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="TB">Très bien</SelectItem><SelectItem value="B">Bien</SelectItem><SelectItem value="M">Moyen</SelectItem><SelectItem value="I">Insuffisant</SelectItem></SelectContent></Select></label><label>Observations générales<Textarea /></label><label>Élèves nécessitant une attention particulière<Textarea placeholder="Sélectionnez et commentez les situations utiles…" /></label></div><div className="teacher-submit"><Button variant="outline" className="secondary-action" onClick={() => onToast("Brouillon enregistré", "Le rapport reste modifiable avant soumission.")}>Enregistrer le brouillon</Button><Button className="primary-action" onClick={() => onToast("Rapport soumis", "Le rapport P1 est transmis à l’administration.")}>Soumettre le rapport</Button></div></section>;
  if (view === "monitoring") return <section className="teacher-suite"><Header title="Suivi des saisies" detail="Administration · Année 2026-2027 · P1" /><div className="submission-kpis"><div><strong>82 %</strong><span>Notes soumises</span></div><div><strong>94 %</strong><span>Présences complétées</span></div><div><strong>76 %</strong><span>Évaluations complétées</span></div><div><strong>68 %</strong><span>Rapports soumis</span></div></div><div className="teacher-student-list"><article><strong>M. Kabila · 7e A · Mathématiques</strong><Chip>Terminé</Chip><button onClick={() => onNavigate("validation")}>Voir</button></article><article><strong>Mme Marie · 7e A · Français</strong><Chip tone="warning">En cours</Chip><button onClick={() => onToast("Rappel envoyé", "Un rappel de saisie a été envoyé à Mme Marie.")}>Rappeler</button></article></div></section>;
  if (view === "validation") return <section className="teacher-suite"><Header title="Validation des notes" detail="Administration · 7e A · Mathématiques · P1 · Soumise le 23 août 2026 à 14:32" onBack={() => onNavigate("monitoring")} /><div className="grade-entry-list">{learners.map((s) => <article key={s.id}><strong>{s.name}</strong><span>{s.p1 || "—"}/10</span><Chip tone={s.name === "Grâce Mulumba" ? "warning" : "success"}>{s.name === "Grâce Mulumba" ? "À vérifier" : "Validée"}</Chip><button onClick={() => onToast("Journal d’audit", "Toute correction exigera une ancienne valeur, une nouvelle valeur et un motif.")}>Corriger</button></article>)}</div></section>;
  if (view === "reportcard") return <section className="teacher-suite official-report"><p>LES ANGES DU CIEL</p><small>École catholique — ECCATH</small><h1>RELEVÉ DE CÔTES</h1><span>Année scolaire : 2026-2027 · Période : P1</span><div><strong>Élève : Jean Kabila</strong><strong>Classe : 7e A</strong></div><table><thead><tr><th>Cours</th><th>Maximum</th><th>Points obtenus</th></tr></thead><tbody><tr><td>Mathématiques</td><td>10</td><td>8</td></tr><tr><td>Français</td><td>10</td><td>7</td></tr><tr><td>Anglais</td><td>10</td><td>9</td></tr><tr><td>Histoire</td><td>5</td><td>4</td></tr></tbody></table><strong>Total : 526 / 700 · Pourcentage : 75,14 % · Rang : 4e / 34</strong><p>Ce relevé est généré par le système de gestion de l’établissement. Il ne constitue pas le bulletin officiel délivré par la Sous-division.</p><div className="teacher-submit"><Button className="primary-action" onClick={() => window.print()}>Imprimer</Button><Button variant="outline" className="secondary-action" onClick={() => onToast("Téléchargement", "La préparation PDF sera reliée au générateur de documents sécurisé.")}>Télécharger PDF</Button></div></section>;
  if (view === "results" || view === "studentresults") return <section className="teacher-suite"><Header title={view === "results" ? "Résultats" : "Résultats annuels de Jean Kabila"} detail={view === "results" ? "7e A · P1 · Points maximum : 700" : "2026-2027 · 7e A · résultats calculés à partir des semestres"} onBack={() => onNavigate("dashboard")} /><div className="result-kpis"><div><strong>34</strong><span>élèves</span></div><div><strong>61,8 %</strong><span>Moyenne de classe</span></div><div><strong>84,29 %</strong><span>Meilleur résultat</span></div><div><strong>76 %</strong><span>Taux de réussite</span></div></div><div className="teacher-student-list"><article><strong>1 · Sarah Mbayo</strong><span>590 / 700 · 84,29 %</span><Chip>Réussi</Chip></article><article><strong>2 · Jean Kabila</strong><span>526 / 700 · 75,14 %</span><Chip>Réussi</Chip></article><article><strong>3 · Patrick K.</strong><span>510 / 700 · 72,86 %</span><Chip>Réussi</Chip></article></div></section>;
  return null;
}
